---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
source('analysis.r')
```

## Conclusions

The most interesting trends which appeared in the data analyzed in this section are:

- Students who enter university with college credit tend to be in classes with higher GPAs than students entering unversity without college credits
- Students hoping to enter Computer Science programs at the University of Washington or Virginia Tech will have similar GPAs in their first term (at either school)
- Students hoping to enter Business programs at the University of Washington or Virginia Tech might have a harder time at VT for introductory level courses, but might enter the more gently graded higher level courses faster than their counterparts at UW.

It is worth noting that this data is taken from class averages, which might not best reflect strictly freshmen behaviors, as introductory level classes can be taken at any point in a student's university carrer.